% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\StevenSummey\Documents\MATLAB\Omics Analyses\A 3in1 omics data visualization and analytical method\ab126omics.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Aug-2023 16:07:29

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = "prot_acc";
%opts.DataRange = "A2:H419";
opts.DataRange = "A2:K451";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "DS321DEC2022", "Var5", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre", "AB126_EV","AB126_Pep"];
opts.SelectedVariableNames = ["DS321DEC2022", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"];
opts.VariableTypes = ["char", "char", "char", "string", "char", "string", "string", "string",...
    "string","string","string"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "DS321DEC2022", "Var5", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "DS321DEC2022", "Var5", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"], "EmptyFieldRule", "auto");

% Import the data
ab126omics = readmatrix("C:\Users\StevenSummey\OneDrive - Aruna Bio\MATLAB\Omics_Analyses\A 3in1 omics data visualization and analytical method\ab126omics.xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts
%% Transform to single string array
A = vertcat(ab126omics(:,1), ab126omics(:,2), ab126omics(:,3), ab126omics(:,4),...
    ab126omics(:,5), ab126omics(:,6), ab126omics(:,7)); %, ab126omics(:,8));
A(A == "") = []; 
[s,~,j] = unique(A); 
hitStore = strings(30,1); %top # hits
for i = 1:numel(hitStore)
    [s,~,j] = unique(A); 
    hitStore(i) = string(s{mode(j)}); %need to readjust excel file to remove acc
    A(A == hitStore(i)) = []; 
end
%% Get Scores

% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\StevenSummey\Documents\MATLAB\Omics Analyses\A 3in1 omics data visualization and analytical method\ab126omics.xlsx
%    Worksheet: prot_score
%
% Auto-generated by MATLAB on 24-Aug-2023 16:17:53

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = "prot_score";
%opts.DataRange = "A2:H419";
opts.DataRange = "A2:K451";

% Specify column names and types
opts.VariableNames = ["DS306APR2023", "DS313APR2023", "DS20APR2023", "DS321DEC2022", "DS329MAR2023", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double",...
    "double","double","double"];

% Import the data
ab126omics_Score = readtable("C:\Users\StevenSummey\OneDrive - Aruna Bio\MATLAB\Omics_Analyses\A 3in1 omics data visualization and analytical method\ab126omics.xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts

%% Get full prot_acc

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = "prot_acc";
%opts.DataRange = "A2:H419";
opts.DataRange = "A2:K451";

% Specify column names and types
opts.VariableNames = ["DS306APR2023", "DS313APR2023", "DS20APR2023", "DS321DEC2022", "DS329MAR2023", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string",...
    "string","string","string"];

% Specify variable properties
opts = setvaropts(opts, ["DS306APR2023", "DS313APR2023", "DS20APR2023", "DS321DEC2022", "DS329MAR2023", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["DS306APR2023", "DS313APR2023", "DS20APR2023", "DS321DEC2022", "DS329MAR2023", "DS330SEP2022", "DS312JUN2023", "DS316JUN2023",...
    "AB126_Pre","AB126_EV","AB126_Pep"], "EmptyFieldRule", "auto");

% Import the data
ab126omics_Prot = readtable("C:\Users\StevenSummey\OneDrive - Aruna Bio\MATLAB\Omics_Analyses\A 3in1 omics data visualization and analytical method\ab126omics.xlsx", opts, "UseExcel", false);
% Clear temporary variables
clear opts
%%
sampleNames = string(ab126omics_Score.Properties.VariableNames)';
proteinNames = hitStore; 
scoreStore = zeros(size(sampleNames,1),size(proteinNames,1)); 
for i = 1:numel(sampleNames)

    actinINDX = find(ab126omics_Prot.(sampleNames(i)) == "ACTB_BOVIN");

    if isempty(actinINDX)
        actin_norm = 1; 
    else
        actin_norm = ab126omics_Score.(sampleNames(i))(actinINDX);
    end

    for j = 1:numel(proteinNames)
        protINDX = find(ab126omics_Prot.(sampleNames(i)) == proteinNames(j));
        if isempty(protINDX)
            scoreStore(i,j) = 0; 
        else
            scoreStore(i,j) = (ab126omics_Score.(sampleNames(i))(protINDX))./ actin_norm;
            if scoreStore(i,j) > 5
                scoreStore(i,j) = 5; 
            end
        end
    end
end

%%
 A = cellfun(@(x) strsplit(x,'_'), proteinNames, 'UniformOutput', false);
 proteinNames = cellfun(@(x) x{1}, A, 'UniformOutput', false);
 proteinNames = string(proteinNames);
%%
MF = table2cell(MF);
A = cellfun(@(x) strsplit(x,','), MF(:,4), 'UniformOutput', false);
B = cellfun(@(x) erase(x{2},"%"), A, 'UniformOutput', false);
% percentages = cellfun(@(x) x{1}, A, 'UniformOutput', false);
C = cellfun(@(x) strsplit(x{1}," "), A, 'UniformOutput', false);
D = cellfun(@(x) x{1}, C,'UniformOutput', false);
count = str2double(D);
percentages = str2double(B);
MF = cell2table(MF);
MF.Properties.VariableNames(1) = "Category";
MF.Properties.VariableNames(2) = "Sample";
MF.Properties.VariableNames(3) = "Term";
MF.Properties.VariableNames(4) = "Usage";
MF.Percentages = percentages; 
MF.Count = count; 

%%
slimGOCC = table2cell(slimGOCC);
A = cellfun(@(x) strsplit(x,'('), slimGOCC(:,3), 'UniformOutput', false);
B = cellfun(@(x) x{1}, A, 'UniformOutput', false);
slimGOCC = cell2table(slimGOCC);
slimGOCC.Properties.VariableNames(1) = "Category";
slimGOCC.Properties.VariableNames(2) = "Sample";
slimGOCC.Properties.VariableNames(3) = "Term";
slimGOCC.Properties.VariableNames(4) = "Usage";
slimGOCC.Properties.VariableNames(5) = "Percentages";
slimGOCC.Properties.VariableNames(6) = "Count";
slimGOCC.Term = B; 
%%
writetable(slimGOCC,"C:\Users\StevenSummey\OneDrive - Aruna Bio\Characterization\Proteomics\slimGO_CC.xlsx")
%%
%writetable(MF,"C:\Users\StevenSummey\OneDrive - Aruna Bio\Characterization\Proteomics\slimGO_MF.xlsx")