function [fitresult, gof] = createFit_Concentration(invDF, loadedConc)
%CREATEFIT(INVDF100NM,LOADEDCONCALP)
%  Create a fit.
%
%  Data for 'BeadConcentrationLinearity_ALP' fit:
%      X Input: invDF100nm
%      Y Output: loadedConcALP
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Dec-2022 15:39:17


%% Fit: 'BeadConcentrationLinearity_ALP'.
[xData, yData] = prepareCurveData( invDF, loadedConc);

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'BeadConcentrationLinearity_ALP' );
% h = plot( fitresult, xData, yData );
% legend( h, 'loadedConcALP vs. invDF100nm', 'BeadConcentrationLinearity_ALP', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'invDF100nm', 'Interpreter', 'none' );
% ylabel( 'loadedConcALP', 'Interpreter', 'none' );
% grid on


